-- Staging seed: Feedback Center fixtures
-- Idempotent deterministic data covering reporter, host/admin triager, and unauthorized user.

insert into public.user_roles (user_id, role) values
  ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'host'),
  ('cccccccc-cccc-cccc-cccc-cccccccccccc', 'admin')
on conflict (user_id, role) do nothing;

insert into public.feedback_items (
  id,
  type,
  title,
  description_md,
  steps_to_reproduce_md,
  expected_result_md,
  actual_result_md,
  problem_md,
  proposed_outcome_md,
  status,
  priority,
  module_id,
  route_path,
  reporter_user_id,
  assignee_user_id,
  triage_notes,
  browser_meta,
  created_at,
  updated_at,
  closed_at
) values
  (
    'f1000000-0000-0000-0000-000000000001',
    'bug',
    'Module card summary does not refresh after submission',
    'After submitting feedback, the summary card still shows stale counts until page reload.',
    '1. Open Feedback Center\n2. Submit a new item\n3. Check dashboard summary card',
    'Summary should increment immediately after submission.',
    'Summary remains unchanged until hard refresh.',
    null,
    null,
    'new',
    'high',
    'feedback-center',
    '/modules/feedback-center',
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    null,
    null,
    '{"userAgent":"staging-fixture"}'::jsonb,
    '2026-02-24T00:00:00Z'::timestamptz,
    '2026-02-24T00:00:00Z'::timestamptz,
    null
  ),
  (
    'f1000000-0000-0000-0000-000000000002',
    'feature',
    'Add module-specific feedback templates',
    'Requesting starter templates to speed up common report types.',
    null,
    null,
    null,
    'Users need guidance so reports are actionable on first submit.',
    'Provide optional templates per feedback type and module context.',
    'triaged',
    'medium',
    'module-requests',
    '/modules/module-requests',
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    'Added to backlog for Q2 UX improvements.',
    '{"userAgent":"staging-fixture"}'::jsonb,
    '2026-02-25T00:00:00Z'::timestamptz,
    '2026-02-26T00:00:00Z'::timestamptz,
    null
  ),
  (
    'f1000000-0000-0000-0000-000000000003',
    'feedback',
    'Great onboarding flow on me-tools',
    'The me-tools defaults made it easy to discover profile setup tasks.',
    null,
    null,
    null,
    null,
    null,
    'in_progress',
    'low',
    'profile-completion',
    '/me',
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    'cccccccc-cccc-cccc-cccc-cccccccccccc',
    'Collecting more examples before drafting UX adjustments.',
    '{"userAgent":"staging-fixture"}'::jsonb,
    '2026-02-25T12:00:00Z'::timestamptz,
    '2026-02-26T12:00:00Z'::timestamptz,
    null
  ),
  (
    'f1000000-0000-0000-0000-000000000004',
    'module_request',
    'Request lightweight retros module',
    'Would like a simple space to run async weekly retros in-portal.',
    null,
    null,
    null,
    'Teams need a consistent retro format with trackable outcomes.',
    'Add a Retros module with prompts, action items, and owner assignment.',
    'done',
    'medium',
    null,
    '/modules/feedback-center',
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    'Captured as candidate for future module-spec workflow.',
    '{"userAgent":"staging-fixture"}'::jsonb,
    '2026-02-25T18:00:00Z'::timestamptz,
    '2026-02-26T18:00:00Z'::timestamptz,
    null
  ),
  (
    'f1000000-0000-0000-0000-000000000005',
    'feedback',
    'Closing stale note for archival test',
    'Used to validate closed-state rendering and filtering.',
    null,
    null,
    null,
    null,
    null,
    'closed',
    'low',
    null,
    '/modules/feedback-center',
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    'Closed after confirming no follow-up needed.',
    '{"userAgent":"staging-fixture"}'::jsonb,
    '2026-02-15T00:00:00Z'::timestamptz,
    '2026-02-20T00:00:00Z'::timestamptz,
    '2026-02-20T00:00:00Z'::timestamptz
  )
on conflict (id) do update set
  type = excluded.type,
  title = excluded.title,
  description_md = excluded.description_md,
  steps_to_reproduce_md = excluded.steps_to_reproduce_md,
  expected_result_md = excluded.expected_result_md,
  actual_result_md = excluded.actual_result_md,
  problem_md = excluded.problem_md,
  proposed_outcome_md = excluded.proposed_outcome_md,
  status = excluded.status,
  priority = excluded.priority,
  module_id = excluded.module_id,
  route_path = excluded.route_path,
  reporter_user_id = excluded.reporter_user_id,
  assignee_user_id = excluded.assignee_user_id,
  triage_notes = excluded.triage_notes,
  browser_meta = excluded.browser_meta,
  updated_at = excluded.updated_at,
  closed_at = excluded.closed_at;
